import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const tours = [
['bot-turu','Bot Turu','Boat Tour','Bootstour','Прогулка на лодке','Tekne Turları','Günü denizde geçirmek isteyenler için Antalya kıyılarında keyifli bir tekne deneyimi.','A relaxed boat experience along Antalya’s coast.','Entspannte Bootsfahrt entlang der Küste von Antalya.','Спокойная прогулка на лодке вдоль побережья Антальи.','01'],
['jet-ski','Jet Ski','Jet Ski','Jetski','Гидроцикл','Deniz Macera','Akdeniz’in berrak sularında yüksek tempolu bir jet ski deneyimi.','A high-energy jet ski experience in the Mediterranean.','Actionreiches Jetski-Erlebnis im Mittelmeer.','Драйв на гидроцикле в Средиземном море.','02'],
['parasut','Parşüt','Parasailing','Parasailing','Парасейлинг','Hava Macera','Antalya sahilinde parasailing ile denizin üzerinde yükselin.','Fly above the sea with parasailing.','Schweben Sie beim Parasailing über dem Meer.','Поднимитесь над морем на парасейлинге.','03'],
['kanepe-su-sporlari','Kanepe Su Sporları','Ringo Water Sports','Wassersport Sofa','Водный диван','Deniz Macera','Grupça eğlenceli, hareketli bir su sporu deneyimi.','A fun group water-sports ride.','Ein actionreicher Wassersport für Gruppen.','Весёлое групповое водное развлечение.','04'],
['banana','Banana','Banana Boat','Bananenboot','Банан','Deniz Macera','Aile ve arkadaş grupları için eğlenceli banana boat aktivitesi.','A fun banana boat ride for friends and families.','Spaß für Familien und Freunde auf dem Bananenboot.','Весёлая поездка на банане для друзей и семьи.','05'],
['vip-tur','VIP Tur','VIP Tour','VIP-Tour','VIP тур','VIP Deneyimler','Daha özel ve kişiselleştirilmiş bir Antalya deneyimi.','A premium and personalized Antalya experience.','Ein exklusives und persönliches Antalya-Erlebnis.','Премиальный индивидуальный отдых в Анталье.','06'],
['antalya-kemer-bot-turu','Antalya Kemer Bot Turu','Antalya Kemer Boat Tour','Antalya Kemer Bootstour','Лодочная экскурсия Анталья-Кемер','Tekne Turları','Antalya’dan Kemer yönüne uzanan koylar eşliğinde tekne gezisi.','A scenic boat day from Antalya toward Kemer.','Bootstag von Antalya Richtung Kemer.','Морская прогулка из Антальи в сторону Кемера.','07'],
['green-canyon-5-1','Green Canyon (5+1)','Green Canyon (5+1)','Green Canyon (5+1)','Green Canyon (5+1)','Doğa Turları','Oymapınar Gölü ve Green Canyon’da doğayla iç içe tekne deneyimi.','A nature boat experience in Green Canyon.','Naturerlebnis im Green Canyon.','Прогулка по каньону Грин-Каньон.','08'],
['green-canyon','Green Canyon','Green Canyon','Green Canyon','Грин-Каньон','Doğa Turları','Toros Dağları arasındaki Green Canyon’da sakin tekne gezisi.','A peaceful boat trip through Green Canyon.','Ruhige Bootsfahrt durch den Green Canyon.','Спокойная прогулка по Грин-Каньону.','09'],
['sun-set','Sun Set','Sunset Cruise','Sonnenuntergangsfahrt','Закатный круиз','Tekne Turları','Akdeniz’de gün batımını deniz üzerinden izleyin.','Watch the Mediterranean sunset from the sea.','Sonnenuntergang auf dem Mittelmeer.','Встречайте закат в море.','10'],
['amon-spa','Amon Spa','Amon Spa','Amon Spa','Amon Spa','Wellness & Spa','Spa atmosferinde dinlenme ve yenilenme deneyimi.','A relaxing spa and wellness experience.','Entspannendes Spa- und Wellness-Erlebnis.','Расслабляющий спа-отдых.','11'],
['crown-spa','Crown Spa','Crown Spa','Crown Spa','Crown Spa','Wellness & Spa','Hamam, sauna ve spa ritüelleriyle rahatlama deneyimi.','Relax with hammam, sauna and spa rituals.','Entspannung mit Hamam, Sauna und Spa.','Расслабление в хамаме, сауне и спа.','12'],
['combo-4-1','Combo (4+1)','Combo (4+1)','Combo (4+1)','Комбо (4+1)','Kombine Turlar','Birden fazla deniz aktivitesini tek pakette birleştiren deneyim.','A multi-activity sea package.','Ein Kombipaket mit mehreren Wasseraktivitäten.','Комбо-пакет с водными активностями.','13'],
['combo-5-1','Combo (5+1)','Combo (5+1)','Combo (5+1)','Комбо (5+1)','Kombine Turlar','Tekne ve su sporlarını bir araya getiren hareketli paket.','A lively boat and water-sports combo.','Actionreiches Boot- und Wassersportpaket.','Активный комбо-тур с лодкой и водными развлечениями.','14'],
['diving','Diving','Diving','Tauchen','Дайвинг','Deniz Macera','Akdeniz’in su altı dünyasını keşfetmek için dalış deneyimi.','Explore the underwater world of the Mediterranean.','Entdecken Sie die Unterwasserwelt des Mittelmeers.','Исследуйте подводный мир Средиземного моря.','15'],
['maldiv','Maldiv','Maldiv','Maldiv','Мальдивы','Özel Deneyimler','Turkuaz sular ve tropik atmosfer temalı özel kaçış deneyimi.','A turquoise-water escape experience.','Ein tropischer Ausflug mit türkisfarbenem Wasser.','Отдых в атмосфере бирюзовых вод.','16'],
['antalya-akvaryum','Antalya Akvaryum','Antalya Aquarium','Antalya Aquarium','Аквариум Антальи','Aile & Eğlence','Aileler için Antalya Akvaryum’da deniz yaşamını keşfedin.','Discover marine life at Antalya Aquarium.','Entdecken Sie die Meereswelt im Antalya Aquarium.','Откройте морской мир в аквариуме Антальи.','17'],
['pamukkale','Pamukkale','Pamukkale','Pamukkale','Памуккале','Kültür Turları','Travertenler ve Hierapolis Antik Kenti’ni keşfeden kültür ve doğa gezisi.','Explore Pamukkale travertines and Hierapolis.','Besuchen Sie die Travertine und Hierapolis.','Посетите травертины Памуккале и Иераполис.','18'],
['antalya-city-tur','Antalya City Tur','Antalya City Tour','Antalya Stadtrundfahrt','Экскурсия по Анталье','Şehir Turları','Antalya’nın tarihi ve doğal güzelliklerini bir araya getiren şehir turu.','Discover Antalya’s historic and scenic highlights.','Entdecken Sie die Highlights von Antalya.','Откройте исторические и природные места Антальи.','19'],
['jeep-safari','Jeep Safari','Jeep Safari','Jeep-Safari','Джип-сафари','Doğa Macera','Toroslarda 4x4 araçlarla toprak yollar ve panoramik manzaralar.','4x4 adventure through the Taurus Mountains.','4x4-Abenteuer im Taurusgebirge.','Джип-сафари в Таврских горах.','20'],
['quard-safari','Quard Safari','Quad Safari','Quad-Safari','Квад-сафари','Doğa Macera','Arazi parkurlarında ATV/Quad ile adrenalin dolu safari.','An adrenaline-filled quad adventure.','Adrenalinreiche Quad-Tour.','Адреналиновое сафари на квадроциклах.','21'],
['delphin','Delphin','Dolphin Experience','Delfin-Erlebnis','Дельфины','Deniz Turları','Akdeniz’de yunusları gözlemleme odaklı aile dostu deneyim.','A family-friendly dolphin experience.','Familienfreundliches Delfinerlebnis.','Семейный тур для наблюдения за дельфинами.','22'],
['fish','Fish','Fishing','Angeln','Рыбалка','Deniz Turları','Akdeniz’de açık deniz balıkçılığı deneyimi.','Deep-sea fishing in the Mediterranean.','Hochseefischen im Mittelmeer.','Морская рыбалка в Средиземном море.','23'],
['bugy','Bugy','Buggy Safari','Buggy-Safari','Багги-сафари','Doğa Macera','Doğal parkurlarda buggy ile rehberli off-road macerası.','Guided off-road buggy adventure.','Geführtes Offroad-Buggy-Abenteuer.','Экстремальное сафари на багги.','24']
];
async function main(){
 for(const [slug,tr,en,de,ru,cat,dtr,den,dde,dru,n] of tours){await prisma.tour.upsert({where:{slug},update:{nameTr:tr,nameEn:en,nameDe:de,nameRu:ru,descTr:dtr,descEn:den,descDe:dde,descRu:dru,category:cat,image:`/tours/tour-${n}.jpg`},create:{slug,nameTr:tr,nameEn:en,nameDe:de,nameRu:ru,descTr:dtr,descEn:den,descDe:dde,descRu:dru,category:cat,image:`/tours/tour-${n}.jpg`}})}
 console.log('Seeded 24 tours');
} main().finally(()=>prisma.$disconnect());
