'use client';
import {useMemo,useState} from 'react';
import type {Tour} from '@prisma/client';
export default function HomeClient({tours}:{tours:Tour[]}){const [q,setQ]=useState('');const [cat,setCat]=useState('');const [selected,setSelected]=useState<Tour|null>(null);const [book,setBook]=useState(false);const cats=useMemo(()=>[...new Set(tours.map(t=>t.category))],[tours]);const filtered=tours.filter(t=>(!cat||t.category===cat)&&(!q||(t.nameTr+' '+t.descTr).toLowerCase().includes(q.toLowerCase())));return <>
<div className="top"><div className="container"><span>Antalya • Akdeniz • Türkiye</span><span>TR / EN / DE / RU</span></div></div><header className="nav container"><a href="/"><img className="logo" src="/logo.webp"/></a><nav className="navlinks"><a href="#turlar">Turlar</a><a href="#kategoriler">Kategoriler</a><a href="#hakkimizda">Hakkımızda</a><a href="#iletisim">İletişim</a></nav><a className="btn gold" href="#turlar">Turları Keşfet</a></header>
<section className="hero"><div className="container"><span className="eyebrow">RIVIERA PLUS EXPERIENCE</span><h1>Antalya'yı <span>RIVIERA PLUS</span> ile keşfedin.</h1><p>Tekne turlarından su sporlarına, safari maceralarından wellness deneyimlerine kadar 24 seçilmiş deneyim.</p><div className="search"><div><small>NEREYE?</small><b>Antalya & çevresi</b></div><div><small>DENEYİM</small><select value={cat} onChange={e=>setCat(e.target.value)}><option value="">Tüm kategoriler</option>{cats.map(c=><option key={c}>{c}</option>)}</select></div><div><small>ARA</small><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tur adı veya aktivite..."/></div><button className="btn" onClick={()=>document.getElementById('turlar')?.scrollIntoView({behavior:'smooth'})}>Ara</button></div></div></section>
<div className="strip"><div className="container stripgrid"><div><b>24</b><span>Tur & deneyim</span></div><div><b>4</b><span>Dil</span></div><div><b>Antalya</b><span>Yerel deneyimler</span></div><div><b>7/24</b><span>Rezervasyon talebi</span></div></div></div>
<section id="kategoriler"><div className="container"><div className="head"><div><span className="eyebrow">RIVIERA PLUS</span><h2>Deneyiminizi seçin</h2></div><p>Deniz, doğa, macera, wellness ve kültür seçeneklerini tek yerde keşfedin.</p></div><div className="chips"><button className="chip" onClick={()=>setCat('')}>Tümü</button>{cats.map(c=><button className="chip" key={c} onClick={()=>{setCat(c);document.getElementById('turlar')?.scrollIntoView({behavior:'smooth'})}}>{c}</button>)}</div></div></section>
<section id="turlar"><div className="container"><div className="head"><div><span className="eyebrow">24 SEÇENEK</span><h2>Popüler Turlar</h2></div><p>{filtered.length} tur gösteriliyor</p></div><div className="grid">{filtered.map(t=><article className="card" key={t.id}><div className="photo"><img src={t.image} alt={t.nameTr}/><span className="num">{String(t.id).padStart(2,'0')}</span><span className="cat">{t.category}</span></div><div className="body"><h3>{t.nameTr}</h3><p>{t.descTr}</p><div className="bottom"><div className="price"><small>BAŞLANGIÇ</small><strong>{t.priceTry?`${t.priceTry} ₺`:'Fiyat için iletişime geçin'}</strong></div><button className="details" onClick={()=>setSelected(t)}>Detayları Gör →</button></div></div></article>)}</div></div></section>
<section className="banner"><div className="container"><span className="eyebrow">RIVIERA PLUS TRAVEL AGENCY</span><h2>Antalya'da sıradan bir tatil değil, güzel bir deneyim yaşayın.</h2><p>Turunuzu seçin, fiyatı yönetim panelinden belirleyin ve rezervasyon taleplerinizi kolayca yönetin.</p><a className="btn" href="#turlar">Turları İncele</a></div></section>
<section id="hakkimizda"><div className="container"><div className="head"><div><span className="eyebrow">BİZ KİMİZ?</span><h2>RIVIERA PLUS</h2></div><p>Antalya ve Akdeniz çevresindeki deneyimleri modern bir rezervasyon deneyiminde buluşturmak için tasarlanmış seyahat platformu.</p></div></div></section>
<footer id="iletisim" className="footer"><div className="container footergrid"><div><img src="/logo.webp"/><p>Antalya'nın deneyimlerini keşfedin.</p></div><div><h4>Menü</h4><a href="#turlar">Turlar</a><a href="#kategoriler">Kategoriler</a></div><div><h4>İletişim</h4><a href={`https://wa.me/${process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||'905000000000'}`}>WhatsApp</a><a href="mailto:info@rivieraplus.com">info@rivieraplus.com</a></div><div><h4>Yasal</h4><a href="#">Gizlilik</a><a href="#">KVKK</a><a href="#">Çerezler</a></div></div><div className="container copy">© 2026 RIVIERA PLUS TRAVEL AGENCY</div></footer>
{selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="modalbox" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><img src={selected.image}/><div className="modalbody"><span className="eyebrow">{selected.category}</span><h2>{selected.nameTr}</h2><p>{selected.descTr}</p><p>📍 {selected.pickup} &nbsp; • &nbsp; 🕒 {selected.duration}</p><button className="btn gold" onClick={()=>setBook(true)}>Rezervasyon Talebi</button></div></div></div>}
{book&&selected&&<BookingForm tour={selected} onClose={()=>setBook(false)}/>}</>}
function BookingForm({tour,onClose}:{tour:Tour,onClose:()=>void}){const [sent,setSent]=useState(false);const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,tourId:tour.id})});if(r.ok)setSent(true);else alert('Rezervasyon gönderilemedi.');};return <div className="modal"><div className="modalbox"><button className="close" onClick={onClose}>×</button><div className="modalbody"><span className="eyebrow">REZERVASYON</span><h2>{tour.nameTr}</h2>{sent?<div className="notice">Rezervasyon talebiniz alındı. En kısa sürede sizinle iletişime geçeceğiz.</div>:<form className="form" onSubmit={submit}><input name="name" placeholder="Ad Soyad" required/><input name="email" type="email" placeholder="E-posta" required/><input name="phone" placeholder="Telefon / WhatsApp" required/><input name="date" type="date" required/><div className="two"><input name="adults" type="number" min="1" defaultValue="2"/><input name="children" type="number" min="0" defaultValue="0"/></div><textarea name="note" rows={4} placeholder="Otel, pickup, özel istek..."/><button className="btn gold">Rezervasyon Talebi Gönder</button></form>}</div></div></div>}
